apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
{{- $startTime := now | unixEpoch }}
{{- range $geo_id := .Values.dataset.geo_ids }}
  config-{{ $geo_id }}.yml: |
    data:
      type: geo_dist
      geo_id: {{ $geo_id }}
      path: /data/user_ts_zone_hotspot_combined_zone_{{ $geo_id }}.parquet
      start_timestamp: {{ $startTime }}
      first_record_timestamp: {{ $.Values.dataset.first_record_timestamp }}
      delay_start_seconds: {{ $.Values.dataset.delay_start_seconds }}
      duration: {{ $.Values.dataset.duration | default 20 }}
      num_requests: {{ $.Values.dataset.num_requests | default 10 }}
      no_wait: {{ $.Values.dataset.no_wait | default false }}
    storage:
      local_storage:
        path: "/reports"
        report_file_prefix: geo_id-{{ $geo_id }}-
        detailed_result_file: detailed_results-geo_id-{{ $geo_id }}.csv
    load:
      type: dataset
      num_workers: {{ $.Values.number_of_workers | default 4 }}
    api:
      type: chat
      streaming: true
    server:
      type: vllm
      model_name: {{ $.Values.server.model_name }}
      base_url: {{ $.Values.server.base_url }}
      ignore_eos: true
    metrics:
      type: default
    report:
      request_lifecycle:
        summary: true
        per_stage: false
        per_request: false
      prometheus:
        summary: true
        per_stage: false

{{- end }}
